name: Create Archive
on: 
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Run Python commands
      run: |
        pip install --upgrade pip
        python -m venv env
        env\Scripts\activate.bat
        pip install -r deploy/requirements.txt
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: '7z'
        filename: 'release.7z'
    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["release.7z"]'
